export const project= [

    {
        id:1,
        img:"/images/1.jpg",
        title:"Heading",
        author:"Polkadot",
        url:"",
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
        categories:['nft']
    },
    {
        id:2,
        img:"/images/2.jpg",
        title:"Kusam",
        author:"ksm",
        url:"",
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
        categories:['nft']
    },
    {
        id:3,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },
    {
        id:4,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },
    {
        id:5,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },
    {
        id:6,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },
    {
        id:7,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },
    {
        id:8,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },
    {
        id:9,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },
    {
        id:10,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['nft']
    },

    // Octopus

    {
        id:11,
        img:"/images/9.jpg",
        title:"Polkadot",
        author:"polka",
        url:"",
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi",
        categories:['octopus']
    },
    {
        id:12,
        img:"/images/8.jpg",
        title:"kusam",
        author:"ksm",
        url:"",
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi",
        categories:['octopus']
    },
    {
        id:13,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },
    {
        id:14,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },
    {
        id:15,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },
    {
        id:16,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },
    {
        id:17,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },
    {
        id:18,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },
    {
        id:19,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },
    {
        id:20,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['octopus']
    },

    // Infrastructure

    {
        id:21,
        img:"/images/6.jpg",
        title:"Moonbeam",
        author:"monn",
        url:"",
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
        categories:['infrastructure']
    },
    {
        id:22,
        img:"/images/5.jpg",
        title:"astar",
        author:"astar",
        url:"",
        description:"Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
        categories:['infrastructure']
    },
    {
        id:23,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },
    {
        id:24,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },
    {
        id:25,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },
    {
        id:26,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },
    {
        id:27,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },
    {
        id:28,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },
    {
        id:29,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },
    {
        id:30,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['infrastructure']
    },

    // Wallets

    {
        id:31,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:32,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:33,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:34,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:35,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:36,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:37,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:38,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:39,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },
    {
        id:40,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['wallets']
    },

    // Validators

    {
        id:41,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:42,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:43,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:44,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:45,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:46,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:47,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:48,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:49,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
    {
        id:50,
        img:"",
        title:"",
        author:"",
        url:"",
        description:"",
        categories:['validators']
    },
]